version: '3.4'

volumes:
  jenkins_data:

services:
  jenkins:
    container_name: jenkins
    image: niiiiiiiice/jenkins-with-docker:1.2
    build:
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
        DOCKER_LOGIN: ${HOST_GID}
        DOCKER_PASS: ${HOST_GID}
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8050:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /usr/local/jenkins-conf:/usr/local/jenkins-conf
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKER_CONFIG=/root/.docker/config.json
