version: '3.4'

volumes:
  jenkins_data:

services:
  jenkins:
    image: niiiiiiiice/jenkins-with-docker:1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8050:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /usr/local/jenkins-conf:/usr/local/jenkins-conf
      - /var/run/docker.sock:/var/run/docker.sock
